apiVersion: v1
kind: Secret
metadata:
  name: slipchuk-private-registry-key
  namespace: slipchuk
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyVnlhR2w1YzJ4cGNHTm9kV3M2WkdOcmNsOXdZWFJmWDJod2IxVnpRWFZWUTNOVE1UaDViWEEzUWt0RFowNU5hVjlyIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
